### ISSUE TITLE
Suggestion: NFL in Particular

### ISSUE THREAD

**Issue by BKeyport** [jclarke0000/MMM-MyScoreboard#11]
Love the app! I’ve got it working with everything but american football due to the single day aspect. American football is the odd case of multiple days being considered the same day for schedule purposes. Would be nice to have it consider the NFL special case of Week # games, and have week # all display as one “day” (Thursday through Monday games each week) - NCAAF is also in a like schedule but I don't know what it is.

**Comment by jclarke0000** [comment]
My intention was to never have this situation in the module.  It is only ever intended to show the current day's games, regardless of sport.  Otherwise the list of games gets really long, spoiling the minimal space requirement I originally had for the module.

If this is something you would like, the Sportsnet feed does this by default when you request NFL and CFL.  Feel free to fork the module and customize it for your own needs.
